### ISSUE TITLE
Web interface for system load

### ISSUE THREAD

**Issue by Sabryr** [NAICNO/Jobanalyzer#53]
As a deliverable, we need to provide a load dash board for all systems run by NAIC partners. For this I propose the following workflow.
1. Sonar generates a system load summary file in a passable format , e.g. json 
2. At defined interval this files is pushed to a specific Github branch. 
4. This triggers a CI/CD and creates artifacts with plots etc..
5. A github page is updated with this information

- sabryr has tested the concept : https://naicno.github.io/Load-dashboard/
- we can get help from the  person joining temporarily to implement this

Any thoughts ?

**Comment by lars-t-hansen** [comment]
Just a minor correction, sonar won't deliver the data but sonalyze will (based on sonar data), it's useful to keep these separated, also in discussion.  The raw sonar data aren't suitable for this type of direct analysis at all, that's why we have sonalyze to cook them and present them.

This use case fits in with a number of the other abstractions built on top of sonalyze, notably discussed in #37.  There are already similar analysis jobs running and producing data (looking for zombie jobs and programs that abuse the system).   Also see README.md, this is essentially the same as the current_utilization / historical_utilization use cases outlined there.

This use case needs more meat on the bone, wrt what you specifically define as "system load", and especially how you want to define that on a multi-node system.  (There are many quantities we could plot, and we can probably get away with plotting a few together, if we want to.)  JSON output is fine (and can be added cheaply) but is a secondary concern.

**Comment by lars-t-hansen** [comment]
Evolving task list:

- [ ] #51 
- [ ] #67 
- [ ] #68
- [ ] Implement subprocess, parsing, and report generation logic in the `naicreport` component
- [ ] Implement some kind of github integration, this may possibly be a shell script that invokes naicreport and git

**Comment by lars-t-hansen** [comment]
The source for Sabry's PoC has JSON data that looks like this:
```
[
    { "x": 1, "y": 5 },
    { "x": 2, "y": 8 },
    { "x": 10, "y": 102 }
]
```
This basically defines a line plot and then the plotting code fills in the area under the curve.  I think we need  more meat on the bone here.

First, the data per host should probably be emitted to separate files, named by the host is most sensible.  So, "ml1.hpc.uio.no.json" will have the data for that host.  The client can choose to plot things together, should it choose to.

Second, it's a question of what quantities we plot, exactly.  We have a *lot* of data to choose from.  It may be that we want to plot multiple data streams for a single host together in the same plot: most obviously, CPU utilization, memory utilization, GPU utilization, GPU memory utilization.

I think I'll represent the JSON file for a host like this:
```
{ "rcpu": [ {"x": n, "y": m}, ...],
  "rmem": ...
  "rgpu": ...
  "rgpumem": ...,
  "start": ...,
  "end": ...,
  "host": ...}
```
where `start` and `end` will be the earliest timestamps in the file, x will be labeled consecutively from 0 and indicates time, each point is the bucket for one hour (ie `--hourly` aggregation in sonalyze).  The tricky part is y.  For a first cut it is most sensible to normalize it, that is, the y axis runs from 0% to 100%, where 100% means all system resources are used (so, all gpu memory across all cards, for example).  Whether that makes most sense we'll have to figure out over time.  The names are "rwhatever" because these are the field names used by sonalyze, there's no sense in coming up with different names.  That is, data come out of sonalyze already normalized.

The default date range will (for now) be the last 24 hours, but it'll be easily changeable.

**Comment by lars-t-hansen** [comment]
All the code up to and including json generation has landed in main.

**Comment by lars-t-hansen** [comment]
The code is done and fairly clean.  What remains is integration (see task list above), we need to determine the overall system architecture, as to where data are stored and where cron jobs and web servers run.  This requires a conversation.

**Comment by lars-t-hansen** [comment]
(Specifically, we'll probably bypass the github idea altogether, it's better for a web server to serve this mostly-static content, which can be regenerated from sonar logs if it is lost.)

**Comment by lars-t-hansen** [comment]
The POC for this is up and running, remaining issues of data distribution have been moved to #69.  Closing this as completed.
